version: '3'

services:
  pipeline:
    image: python:3.9-slim
    container_name: ml_pipeline
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      pip install --upgrade pip &&
      sh pipeline.sh
      "